### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by Zeitsperre** [geopython/pygml#5]
Hi there,

I just stumbled upon this after looking for a GDAL-free alternative for reading GML files. I'm wondering if there's interest in publishing a conda-forge package. If so, I can help by drafting a recipe.

Thanks!

**Comment by constantinius** [comment]
I myself do not use conda but I hear that many people do, so I guess it would make sense to add that. I would appreciate if you could add the recipe for that!

**Comment by Zeitsperre** [comment]
See: https://github.com/conda-forge/staged-recipes/pull/16132

**Comment by Zeitsperre** [comment]
Available in conda-forge: https://github.com/conda-forge/pygml-feedstock/
Installable via: `conda install -c conda-forge pygml`
